/*
 *  at_cmd.h - at command definition.
 *
 *  Copyright (C) 2019 Unigroup Spreadtrum & RDA Technologies Co,Ltd.
 *
 *  History:
 *  2019-2-13 Elon Li
 *  Initial version.
*/
#ifndef _AT_CMD_H
#define _AT_CMD_H

#define MAX_AT_RESPONSE 256

#define AT_SETARMLOG "AT+ARMLOG="
#define AT_SETCAPLOG "AT+SPCAPLOG="
#define AT_SETDSPLOG "AT+SPDSPOP="
#define AT_SETLOGLEVEL "AT+SPLOGLEVEL="
#define AT_SETETB "AT+SPCORESIGHT="
#define AT_SETARMPCMDUMP "AT+SPPCMDUMP="
#define AT_SETDSPPCMDUMP "AT+SPDSP="

#define AT_GETARMLOG "AT+ARMLOG?\r"
#define AT_GETCAPLOG "AT+SPCAPLOG?\r"
#define AT_GETDSPLOG "AT+SPDSPOP?\r"
#define AT_GETLOGLEVEL "AT+SPLOGLEVEL?\r"
#define AT_GETETB "AT+SPCORESIGHT?\r"


#define LOG_USER_CMD "1,0," \
"\"" \
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" \
"\"" \
"," \
"\"" \
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" \
"\""
#define LOG_LEVEL_1 "1,1," \
"\"" \
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" \
"\"" \
"," \
"\"" \
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" \
"\""
#define LOG_LEVEL_2 "1,2," \
"\"" \
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" \
"\"" \
"," \
"\"" \
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" \
"\""
#define LOG_DEBUG_CMD "1,3," \
"\"" \
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" \
"\"" \
"," \
"\"" \
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" \
"\""
#define LOG_FULL_CMD "1,5," \
"\"" \
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" \
"\"" \
"," \
"\"" \
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" \
"\""

#endif
